# Where things are
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
data_dir: ./_data
# collections: null

# Outputting
permalink:     /:title.html
paginate: 10
paginate_path: /page:num
timezone:      null

quiet:    false
defaults: []

include: ['_pages']
